### ISSUE TITLE
Trained model for inference available?

### ISSUE THREAD

**Issue by ddomingof** [MaayanLab/L1000toRNAseq#1]
Hi,
Congrats for the publication! I really liked the work.
Is the trained model available for inference? I would like to test it myself.
Thanks

**Comment by sherxie** [comment]
Hi @ddomingof, thank you for your interest. 

The final models used for step 1 (L1000 landmark -> RNA-seq landmark) and step 2 (RNA-seq landmark -> RNA-seq full genome) can be found [here](https://lincs-dcic.s3.amazonaws.com/LINCS-L1000-Transformed/models.zip), which should be a zipped folder with sub-folders containing PyTorch (PTH) files. You should be able to set `step1_exp_index = 38` and `step2_exp_index = 35` in the [scripts/L1000_to_RNAseq.ipynb](https://github.com/MaayanLab/L1000toRNAseq/blob/main/scripts/L1000_to_RNAseq_pipeline.ipynb) file in order to run the code.

**Comment by jmche** [comment]
I download the "LINCS L1000 CycleGAN models" from the https://maayanlab.cloud/sigcom-lincs/#/Download.

It's really hard to use the model since there isn't any data information. Would you provide some data information?
I matched 977 genes using  "GSE92742_Broad_LINCS_gene_info.txt" and "GSE92742_Broad_LINCS_gene_info_delta_landmark.txt" from GSE92742. However, the trained step1 model needs 962 genes and I couldn't know which 962 genes were used. 

I would appreciate it if you could provide the data.
